# About {.unnumbered}

::: callout-note
This report is currently in development. It was last updated on **`r Sys.Date()`**.
:::

This report is a data update for the Richmond Regional Housing Framework, which was [released](https://pharva.com/framework/about-the-framework/) by the Partnership for Housing Affordability (PHA) in January 2020. It will support PHA's ongoing efforts to educate both decision-makers and the public at large about the region's housing needs and opportunities. Data in the report will also help PHA continue to monitor, change, and implement the policy solutions outlined in the Framework.

There are four parts in this report:

1.  Demographic and socioeconomic changes
2.  Housing supply and market changes
3.  Gap analysis
4.  Local summaries

## How to read this report {.unnumbered}

This report is an interactive website with three main columns for navigation:

1.  **Table of contents** (*left*): Search bar and links to all chapters in the report.
2.  **Current chapter** (*center*): Main chapter content.
3.  **Chapter navigation** (*right*): Quick links to subsections within the currently-viewed chapter.

Links to both the previous and next chapter are included at the bottom of each chapter page.

## How to provide feedback on this draft {.unnumbered}

All comments, questions, and suggestions should be emailed to [jonathan\@hdadvisors.net](mailto:jonathan@hdadvisors.net){.email} and [eric\@hdadvisors.net](mailto:eric@hdadvisors.net){.email}.

When applicable, please reference:

-   The chapter number ("Chapter 3")
-   The section/subsection ("3.2.1")
-   The figure/title number ("Figure 3.3")

[Click here](mailto:jonathan@hdadvisors.net,eric@hdadvisors.net) to generate an email in your inbox with the recipients auto-filled.

## Changelog {.unnumbered}

### Release 1.0 {.unnumbered}

*2022-09-15*

First complete draft. Completed PART 3 chapters and local summaries for main four localities.

Still to come:

-   Local summaries for Charles City County, Goochland County, New Kent County, Powhatan County, and additional details for the Town of Ashland
-   Standardize colors across visualizations to match PHA brand palette
-   Make selection of plots interactive
-   Add in dynamic links for all footnotes and citations
-   PDF version of full report and locality summaries

### Release 0.3 {.unnumbered}

*2022-09-11*

Third partial draft. Completed PART 2 chapters. Add dynamic figure and table captions to local summary template.

### Release 0.2 {.unnumbered}

*2022-09-06*

Second partial draft. Migrate from Bookdown project to Quarto project.

### Release 0.1 {.unnumbered}

*2022-08-30*

First partial draft. Test site rendering and hosting. PART 1 chapters fully drafted. Remaining chapters in production.
