# (PART)Demographic and socioeconomic changes {.unnumbered}

## Changes in household characteristics{#part-1-2}

```{r setup}

library(tidyverse)
library(tidycensus)
library(ggplot2)
library(simplevis)
library(tigris)
library(viridis)

# rr includes Charles City, Goochland, New Kent, and Powhatan.

rr <- c("51085", "51760", "51075", "51145", "51087", "51127", "51036", "51041")

pha <- c("51085", "51760", "51087", "51041")

# Set palette colors; may need to find a palette that better complements the PHA branding.

pha_names <- c("Richmond city", "Hanover County", "Henrico County", "Chesterfield County")

geo_colors <- setNames(viridis(4), nm = pha_names)

pal <-colorFactor(palette = c("#440154FF", "#31688EFF","#35B779FF", "#FDE725FF"),
                  levels = c("Richmond City", "Hanover", "Henrico", "Chesterfield"))

tenure <- c("Homeowner", "Renter")

tenure_colors <-setNames(viridis(2), nm = tenure)

```


```{r geography-setup}

va <- counties(state = "VA", year = 2020)

rr_va <- va |> 
  subset(GEOID %in% rr)

pha_va <- va |> 
  subset(GEOID %in% pha)

```

Household formation trends
```{r hh-formation}

# years <- 2016:2020
# 
# b25007_vars <- load_variables(2020, "acs5") |> 
#   filter(str_sub(name, end = 6) %in% "B25007")
# 
# b25007_raw <- map_dfr(years, function(yr){
#   b25007_pull <- get_acs(
#     geography = "county",
#     state = "VA",
#     table = "B25007",
#     year = yr,
#     survey = "acs5",
#     cache_table = TRUE
#   ) |> 
#     mutate(year = yr)
# })
# 
# write_rds(b25007_raw, "data/b25007_raw.rds")

b25007_raw <- read_rds("data/b25007_raw.rds")

b25007_raw <- b25007_raw |> 
  subset(GEOID %in% pha)

b25007_vars_cleaned <- b25007_vars |> 
  separate(label, into = c("est", "total", "tenure", "age"), sep = "!!") |> 
  select(variable = name, tenure, age) |> 
  drop_na() |> 
  mutate(tenure = case_when(
    tenure == "Owner occupied:" ~ "Homeowner",
    tenure == "Renter occupied:" ~ "Renter"
  ))

b25007_data <- b25007_raw |> 
  right_join(b25007_vars_cleaned, by = "variable") |> 
  select(NAME, GEOID, year, tenure, age, estimate, moe)|> 
  mutate(age = case_when(
    age == "Householder 15 to 24 years" ~ "Under 25 years old",
    age == "Householder 25 to 34 years" ~ "25 to 44 years old",
    age == "Householder 35 to 44 years" ~ "25 to 44 years old",
    age == "Householder 45 to 54 years" ~ "45 to 64 years old",
    age == "Householder 55 to 59 years" ~ "45 to 64 years old",
    age == "Householder 60 to 64 years" ~ "45 to 64 years old",
    age == "Householder 65 to 74 years" ~ "65 years and over",
    age == "Householder 75 to 84 years" ~ "65 years and over",
    age == "Householder 85 years and over" ~ "65 years and over"
  ))

b25007_data_grp <- b25007_data |> 
  group_by(NAME, year, tenure, age) |> 
  summarise(estimate = sum(estimate)) |> 
  separate(NAME, into = c("locality", "state"), sep = ",") |> 
  pivot_wider(names_from = year,
              values_from = estimate) |> 
  select(tenure, age, `2016`, `2020`) |> 
  transform(change = `2020` - `2016`) |> 
  group_by(tenure, age) |> 
  summarise(change = sum(change))

ggplot(b25007_data_grp,
       aes(x = age, y = change, fill = tenure)) +
  geom_bar(stat = "identity", position = "dodge") +
  scale_x_discrete(limits = c("Under 25 years old", "25 to 44 years old", "45 to 64 years old", "65 years and over")) +
  scale_y_continuous(labels = number_format(big.mark = ",")) +
  labs(title="Change in households by age and tenure: 2016 to 2020", fill="Tenure") +
  theme(axis.title = element_blank()) +
  scale_fill_manual(values = tenure_colors)


```

Household type and size
```{r hhtype}

# years <- 2016:2020
# 
# b11001_vars <- load_variables(2020, "acs5") |> 
#   filter(str_sub(name, end = 7) %in% "B11001_")
# 
# b11001_raw <- map_dfr(years, function(yr){
#   b11001_pull <- get_acs(
#     geography = "county",
#     state = "VA",
#     table = "B11001",
#     year = yr,
#     survey = "acs5",
#     cache_table = TRUE
#   ) |> 
#     mutate(year = yr)
# })
# 
# write_rds(b11001_raw, "data/b11001_raw.rds")

b11001_raw <- read_rds("data/b11001_raw.rds")

b11001_raw <- b11001_raw |> 
  subset(GEOID %in% pha)

b11001_vars_cleaned <- b11001_vars |> 
  separate(label, into = c("est", "tot", "type", "relationship", "householder"), 
           sep = "!!") |> 
  select(variable = name, type, relationship, householder) |> 
  mutate(
    householder = case_when(
      relationship == "Married-couple family" ~ relationship,
      relationship == "Householder living alone" ~ relationship,
      relationship == "Householder not living alone" ~ relationship,
      TRUE ~ householder),
    relationship = case_when(
      relationship == "Householder living alone" ~ type,
      relationship == "Householder not living alone" ~ type,
      TRUE ~ relationship)
    ) |> 
  mutate(across(.fns = ~str_remove_all(.x, ":"))) |> 
  drop_na()

b11001_data <- b11001_raw |> 
  right_join(b11001_vars_cleaned, by = "variable") |> 
  select(NAME, GEOID, year, "hhtype" = householder, relationship, type, estimate) |> 
  separate(NAME, into = c("locality", "state"), sep = ",") |> 
  pivot_wider(names_from = year,
              values_from = estimate) |> 
  select(locality, hhtype, `2016`, `2020`) |> 
  transform(change = `2020` - `2016`) |> 
  group_by(hhtype) |> 
  summarise(change = sum(change))

hhtype_bar <- ggplot(b11001_data,
       aes(x = reorder(hhtype, -change),
           y = change,
           fill = hhtype)) +
  geom_bar(stat = "identity") + 
  labs(title = "Change in household type: 2016 to 2020") +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.ticks.x = element_blank(),
        legend.position = "none",
        plot.title = element_text(hjust = -1.8)) +
  coord_flip() +
  scale_y_continuous(labels = number_format(big.mark = ","))

ggplotly(hhtype_bar) |> 
  plotly_camera()


```


```{r hh-size}

# years <- 2016:2020
# 
# b25009_vars <- load_variables(2020, "acs5") |> 
#   filter(str_sub(name, end = 6) %in% "B25009")
# 
# b25009_raw <- map_dfr(years, function(yr){
#   b25009_pull <- get_acs(
#     geography = "county",
#     state = "VA",
#     table = "B25009",
#     year = yr,
#     survey = "acs5",
#     cache_table = TRUE
#   ) |> 
#     mutate(year = yr)
# })
# 
# write_rds(b25009_raw, "data/b25009_raw.rds")

b25009_raw <- read_rds("data/b25009_raw.rds")

b25009_raw <- b25009_raw |> 
  subset(GEOID %in% pha)

b25009_vars_cleaned <- b25009_vars |> 
  separate(label, into = c("est", "total", "tenure", "size"), sep = "!!") |> 
  select(variable = name, tenure, size) |> 
  drop_na() |> 
  mutate(tenure = case_when(
    tenure == "Owner occupied:" ~ "Homeowner",
    tenure == "Renter occupied:" ~ "Renter"
  ))

b25009_data <- b25009_raw |> 
  right_join(b25009_vars_cleaned, by = "variable") |>
  select(NAME, GEOID, year, tenure, size, estimate) |> 
  separate(NAME, into = c("locality", "state"), sep = ",") |> 
  mutate(size = case_when(
    size == "1-person household" ~ size,
    size == "2-person household" ~ size,
    size == "3-person household" ~ size, 
    TRUE ~ "4 or more person household"
  )) |> 
  group_by(year, tenure, size) |> 
  summarise(estimate = sum(estimate)) |> 
  pivot_wider(names_from = year, 
              values_from = estimate) |> 
  select(tenure, size, `2016`, `2020`) |> 
  transform(change = `2020` - `2016`) |> 
  group_by(tenure, size) |> 
  summarise(change = sum(change))

hhsize_bar <- ggplot(b25009_data,
       aes(x = size,
           y = change,
           fill = tenure)) +
  geom_bar(stat = "identity", position = "dodge") + 
  labs(title = "Change in household size by tenure: 2016 to 2020") +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.ticks.x = element_blank()) +
  scale_y_continuous(labels = number_format(big.mark = ",")) +
  coord_flip() +
  scale_x_discrete(limits = rev)

ggplotly(hhsize_bar) |> 
  plotly_camera()

```

Households with children
```{r hh-children}

years <- 2016:2020

b25115_vars <- load_variables(2020, "acs5") |>
  filter(str_sub(name, end = 6) %in% "B25115")

b25115_raw <- map_dfr(years, function(yr){
  b25115_pull <- get_acs(
    geography = "county",
    state = "VA",
    table = "B25115",
    year = yr,
    survey = "acs5"
  ) |>
    mutate(year = yr)
})

write_rds(b25115_raw, "data/b25115_raw.rds")

b25115_raw <- read_rds("data/b25115_raw.rds")

b25115_raw <- b25115_raw |> 
  subset(GEOID %in% pha)

b25115_vars_cleaned <- b25115_vars |> 
  separate(label, into = c("est", "total", "tenure", "family", "type", "rel", "children"), sep = "!!") |> 
  select(variable = name, tenure, family, type, rel, children) |> 
  mutate(tenure = case_when(
    tenure == "Owner occupied:" ~ "Homeowner",
    tenure == "Renter occupied:" ~ "Renter"
  )) |> 
  mutate(family = case_when(
    family == "Family households:" ~ "Family household",
    family == "Nonfamily households" ~ "Nonfamily household"
  )) |> 
  mutate(type = case_when(
    type == "Married-couple family:" ~ "Married household",
    rel == "Male householder, no spouse present:" ~ "Single male household",
    rel == "Female householder, no spouse present:" ~ "Single female household", 
    family == "Nonfamily household" ~ "Nonfamily household"
  )) |> 
  mutate(children = case_when(
    rel == "With own children of the householder under 18 years" ~ "With children",
    rel == "No own children of the householder under 18 years" ~ "No children",
    children == "No own children of the householder under 18 years" ~ "No children",
    children == "With own children of the householder under 18 years" ~ "With children",
    family == "Nonfamily household" ~ "Nonfamily household" 
  )) |> 
  select(variable, tenure, family, type, children) |> 
  drop_na()
  

b25115_data <- b25115_raw |> 
  right_join(b25115_vars_cleaned, by = "variable") |> 
  select(NAME, GEOID, year, tenure, type, children, estimate) |> 
  separate(NAME, into = c("locality", "state"), sep = ",") |> 
  pivot_wider(names_from = year,
              values_from = estimate) |> 
  transform(change = `2020` - `2016`) |> 
  select(tenure, type, children, change) |> 
  group_by(tenure, children) |> 
  summarise(change = sum(change))
  
child_bar <- ggplot(b25115_data,
       aes(x = children,
           y = change,
           fill = tenure)) +
  geom_bar(stat = "identity", position = "dodge") + 
  labs(title = "Change in households with children by tenure: 2016 to 2020") +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.ticks.x = element_blank()) +
  scale_y_continuous(labels = number_format(big.mark = ",")) +
  coord_flip() +
  scale_x_discrete(limits = c("With children", "No children", "Nonfamily household"), rev)

ggplotly(child_bar) |> 
  plotly_camera()


```



Households with seniors
```{r hh-seniors}

# Table B11007: Households by Presence of People 65 Years and Over, Household Size and Household Type ??


# years <- 2016:2020
# 
# b11007_vars <- load_variables(2020, "acs5") |> 
#   filter(str_sub(name, end = 6) %in% "B11007")
# 
# b11007_raw <- map_dfr(years, function(yr){
#   b11007_pull <- get_acs(
#     geography = "county",
#     state = "VA",
#     table = "B11007",
#     year = yr,
#     survey = "acs5"
#   ) |> 
#     mutate(year = yr)
# })
# 
# write_rds(b11007_raw, "data/b11007_raw.rds") 

b11007_raw <- read_rds("data/b11007_raw.rds")

b11007_raw <- b11007_raw |> 
  subset(GEOID %in% pha)

b11007_vars_cleaned <- b11007_vars |> 
  separate(label, into = c("est", "total", "senior", "hhsize", "family"), sep = "!!") |> 
  select(variable = name, senior, hhsize, family) |> 
  mutate(family = case_when(
    hhsize == "1-person household" ~ "Alone",
    hhsize == "1-person households" ~ "Alone",
    TRUE ~ family
  )) |> 
  drop_na() |> 
  mutate(senior = case_when(
    senior == "Households with one or more people 65 years and over:" ~ "Senior(s) present",
    senior == "Households with no people 65 years and over:" ~ "No senior present"
  )) |> 
  mutate(across(.fns = ~str_remove_all(.x, ":")))

b11007_data <- b11007_raw |> 
  right_join(b11007_vars_cleaned, by = "variable") |> 
  select(NAME, GEOID, year, senior, hhsize, family, estimate) |> 
  separate(NAME, into = c("locality", "state"), sep = ",") |> 
  pivot_wider(names_from = year,
              values_from = estimate) |> 
  transform(change = `2020` - `2016`) |> 
  select(tenure, type, children, change) |> 
  group_by(tenure, children) |> 
  summarise(change = sum(change))
  

```
