# (PART)Housing supply and market changes {.unnumbered}

## Housing assistance {#part-2-3}

```{r setup}

library(tidyverse)
library(tidygeocoder)
library(leaflet)
library(sf)
library(sp)
library(janitor)
library(viridis)
library(htmlwidgets)
library(scales)
library(lubridate)

```

### Assisted income-restricted rental


```{r nhpd}

# nhpd <- read_csv("data/nhpd_va_subsidies_7_2022.csv") |>
#   clean_names()
# 
# nhpd_clean <- nhpd |>
#   transform(fulladdress = paste(nhpd$street_address, nhpd$city, nhpd$state, nhpd$zip_code, sep= ", ")) |>
#   select(subsidy_name, subsidy_status, subsidy_subname, start_date, end_date, assisted_units, property_name, fulladdress, owner_name, owner_type, target_population, city)
# 
# localities <- c("CHARLES CITY", "CHESTER", "CHESTERFIELD", "GLEN ALLEN", "HENRICO", "HIGHLAND SPRINGS", "MIDLOTHIAN", "NORTH CHESTERFIELD", "Richmond", "RICHMOND", "RICHMOND CITY", "SANDSTON", "ASHLAND", "MECHANICSVILLE")
# 
# nhpd_clean_rr <- nhpd_clean |>
#   subset(city %in% localities)
# 
# nhpd_coded <- nhpd_clean_rr |>
#   geocode(address = fulladdress,
#           method = 'geocodio',
#           full_results = TRUE,
#           unique_only = FALSE,
#           lat = Latitude,
#           long = Longitude)
# 
# nhpd_coded_rr <- nhpd_coded |>
#   mutate(Latitude = case_when(
#     property_name == "NEW MANCHESTER FLATS IX" ~ 37.517602,
#     property_name == "KINGSRIDGE I" ~ 37.551666,
#     property_name == "GRAND OAKS SENIORS" ~ 37.353614,
#     property_name == "IRON BRIDGE ROAD" ~ 37.361812,
#     TRUE ~ Latitude)) |>
#     mutate(Longitude = case_when(
#       property_name == "NEW MANCHESTER FLATS IX" ~ -77.432408,
#       property_name == "KINGSRIDGE I" ~ -77.375593,
#       property_name == "GRAND OAKS SENIORS" ~ -77.457398,
#       property_name == "IRON BRIDGE ROAD" ~ -77.495881,
#       TRUE ~ Longitude))
# 
# write_rds(nhpd_coded_rr, "data/nhpd_rr.csv")

nhpd_coded_rr <- read_rds("data/nhpd_rr.csv")

# nhpd_coded_rr <- nhpd_coded_rr |>
#   st_as_sf(coords = c("Longitude", "Latitude"), crs=4326, remove = FALSE) |>
#   filter(subsidy_status != "Inactive")|>
#   filter(fulladdress != "PO BOX 8585, RICHMOND, VA, 23226")
# 
# subsidyPal <- colorFactor(viridis(8), nhpd_coded_rr$subsidy_name)
# 
# nhpd_map <- leaflet(nhpd_coded_rr) |>
#   addTiles() |>
#   addCircleMarkers(
#     radius = 5,
#     color = ~subsidyPal(subsidy_name),
#     stroke = FALSE, fillOpacity = 0.5)
# 
# saveWidget(nhpd_map, "maps/nhpd_map.html")
# 
# knitr::include_url("maps/nhpd_map.html", height = "500px")

```

```{r subsidy-location}

subsidy <- nhpd_coded_rr |> 
  select(subsidy_name, assisted_units, locality = address_components.county) |> 
  group_by(locality, subsidy_name) |> 
  summarise(units = sum(assisted_units)) |> 
  st_drop_geometry() |> 
  filter(locality != "Charles City County")


ggplot(subsidy,
       aes(x = reorder(subsidy_name, -units),
           y = units,
           fill = subsidy_name)) +
  geom_bar(stat = "identity") +
  facet_wrap(~locality) +
  theme(axis.title = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank()) +
  labs(title = "Federally assisted units by subsidy and locality", fill = "Subsidy name") +
  scale_y_continuous(labels = number_format(big.mark = ","))


```

```{r public-housing}

ph <- nhpd_coded_rr |> 
  filter(subsidy_name == "Public Housing") 

leaflet(ph) |> 
  addTiles() |> 
  addCircleMarkers(
    radius = ~assisted_units/100
  )


```

### Housing Choice Vouchers

```{r hcv}

# Download HCV geojson from HUD - 7.28.22

# HCV as a Percent of Renter Occupied Housing Units

pha <- c("041", "760", "085", "087")

hcv <- st_read("data/va_hcv_tract.geojson") |> 
  clean_names() |> 
  subset(county %in% pha)

mapview::mapview(hcv, zcol= "hcv_public_pct")



```

## Rent relief and mortgage relief

```{r rmrp}

# Email gabriella.vazquez@dhcd.virginia.gov for data on RRP - breakdown of households helped in Hanover, Henrico, and Richmond --- consider including other localities

# Email Jessica about Chesterfield rent relief program.

rrp <- read_csv("data/rrp_data.csv")|> 
  mutate(avgpayment = spent/payments) |> 
  filter(locality == "Hanover County" | locality == "Henrico County" | locality == "Richmond") |> 
  mutate(date = mdy(date))

ggplot(rrp,
       aes(x = date,
           y = payments,
           fill = locality)) +
  geom_bar(stat = "identity") + 
  facet_wrap(~locality) +
  theme(axis.title = element_blank(),
        axis.text.x = element_text(angle = 90, vjust = 1, hjust = 1)) +
  labs(title = "Rent relief payments by locality") +
  scale_y_continuous(labels = number_format(big.mark = ","))


```
```{r rrp-payment}

ggplot(rrp,
       aes(x = date,
           y = avgpayment,
           fill = locality)) +
  geom_bar(stat = "identity") + 
  facet_wrap(~locality) +
  theme(axis.title = element_blank(),
        axis.text.x = element_text(angle = 90, vjust = 1, hjust = 1)) +
  labs(title = "Average assistance by month and locality") +
  scale_y_continuous(labels = dollar_format())

```
Affordable homeownership

```{r aff-ho}

# MWCLT, BHC, project:HOMES, Southside, Habitat - WAITING ON DATA

# Ask for number of units produced each year from 2019 to now

# Average home price each year?

```

Changes in assisted housing since 2019
