# (PART)Demographic and socioeconomic changes {.unnumbered}

## Components of population change{#part-1-1}

The Richmond region has continued to grow amid the COVID-19 pandemic. 

```{r setup}
library(tidycensus)
library(tidyverse)
library(knitr)
library(janitor)

```

```{r natural}

# PEP does not have data available for 2020 and 2021. There is a gap between 2019 and 2021 because Census uses 2020 as a baseline. 

region <- c(51036, 51041, 51075, 51085, 51087, 51127, 51145, 51760)


pep_change_raw <- get_estimates(
  geography = "county",
  state = "VA",
  variables = c("NATURALINC", "DOMESTICMIG", "INTERNATIONALMIG"),
  time_series = TRUE
)

pep_change_clean <- pep_change_raw %>% 
  mutate(year = # Translate date codes into years
    case_when(
      PERIOD == 1 ~ "2010",
      PERIOD == 2 ~ "2011",
      PERIOD == 3 ~ "2012",
      PERIOD == 4 ~ "2013",
      PERIOD == 5 ~ "2014",
      PERIOD == 6 ~ "2015",
      PERIOD == 7 ~ "2016",
      PERIOD == 8 ~ "2017",
      PERIOD == 9 ~ "2018",
      PERIOD == 10 ~ "2019")) %>%
  mutate(component = # Rename components of change
    case_when(
      variable == "NATURALINC" ~ "Natural increase",
      variable == "DOMESTICMIG" ~ "Domestic migration",
      variable == "INTERNATIONALMIG" ~ "International migration")) %>% 
  select( # Simplify columns
    GEOID,
    year,
    component,
    value
  )

rr_nat_change <- pep_change_clean |> 
  filter(GEOID %in% region) |> 
  filter(component == "Natural increase")

# Maybe manually add in 2021. There will be a gap at 2020 though.

#I've cleaned the 2021 csv and it can be found at the below:

pep_2021 <- read_csv("data/co-est2021-comp-51.csv")


#Create bar chart for each locality showing raw populati

```

```{r migration}

rr_mig_change <- pep_change_clean |> 
  filter(GEOID %in% region) |> 
  filter(component != "Natural increase")



```

```{r pop-change}

```

