# (PART)GAP ANALYSIS {.unnumbered}

## Impact of housing costs on household budgets {#part-3-2}

```{r setup}

library(tidyverse)
library(httr)
library(glue)
library(readxl)
library(janitor)
library(ggplot2)
library(simplevis)
library(stats)

years <- 2015:2018

sumlev <- "050"

dir.create(glue("data/{sumlev}"))

walk(years, ~{
  
  url <- glue("https://www.huduser.gov/PORTAL/datasets/cp/{.x - 4}thru{.x}-{sumlev}-csv.zip")
  
  file <- basename(url)
  
  path <- file.path("data", sumlev, file)
  
  if (!file.exists(path)) {
    GET(url, write_disk(path, overwrite = TRUE), progress(type = "down"))
  }
  
  print(glue("Unzipping {.x}..."))
  unzip(path, exdir = file.path("data", sumlev, .x))
  
})

years <- 2015:2018

# Tables to get
tables <- c(7, 9, paste0(18, LETTERS[1:3]))

# Go through and write out the various tables
walk(tables, function(table) {
  
  mytable <- purrr::map_df(years, function(year) {
    
    # Identify the year-specific folder
    path <- file.path("data", "050", year)
    
    # Find the file - it may be buried so use recursive = TRUE
    file <- list.files(path, pattern = glue("Table{table}.csv"), recursive = TRUE)
    
    # Read in the file quietly
    raw <- read_csv(file.path(path, file), col_types = cols())
    
    # Clean it up
    cleaned <- raw |> 
      clean_names() |> 
      mutate(fips = substr(geoid, 8, 12)) |> 
      separate(name, into = c("county", "state"), sep = ",") |> 
      filter(st == "51") |> 
      pivot_longer(starts_with("T"), 
                   names_to = "code",
                   values_to = "value") |> 
      mutate(id = str_extract(code, "\\d+$"),
             type = str_extract(code, "est|moe")) |> 
      select(-code) |> 
      pivot_wider(names_from = type, values_from = value) |> 
      rename(Estimate = est, MOE = moe) |> 
      mutate(Code := glue("T{table}_est{id}"),
             Year = year) |> 
      select(Code, Year, Estimate, MOE, everything(), -id) |>       
      mutate(fips = case_when(
        fips == "51515" ~ "51019",
        TRUE ~ fips
      )) |> 
      mutate(county = case_when(
        county == "Bedford city" ~ "Bedford County",
        TRUE ~ county
      )) |> 
      subset(fips %in% rr)
    
    # Account for different data dictionaries
    # Find the data dictionary in the appropriate folder
    dict_path <- list.files(path, pattern = "dictionary", recursive = TRUE, full.names = TRUE) 
    
    # Read in the data dictionary and merge
    dict <- read_excel(dict_path, 
                       sheet = glue("Table {table}"))
    
    cleaned_with_dict <- cleaned %>%
      left_join(dict, by = c("Code" = "Column Name"))
    
    cleaned_with_dict
    
  }) 
  
  file_name <- glue("Table{table}_2015to2018.csv")
  
  message(glue("Writing file {file_name}..."))
  
  write_csv(mytable, glue("data/{file_name}"))
  
})

# Consider adding script to remove the "data/050" file folder of zips and tables to create space.

# file.remove()


```

Cost burden
```{r cb-income}

cb_7 <- read_csv("data/Table7_2015to2018.csv") |> 
  clean_names() |> 
  filter(line_type == "Detail") |> 
  select(year, estimate, moe, county, fips, tenure, household_income, household_type, cost_burden) |> 
  mutate(tenure = case_when(
    tenure == "Owner occupied" ~ "Homeowner",
    tenure == "Renter occupied" ~ "Renter"
  )) |> 
  mutate(household_income = case_when(
    household_income == "household income is less than or equal to 30% of HAMFI" ~ "30% AMI or less",
    household_income == "household income is greater than 30% but less than or equal to 50% of HAMFI" ~ "31 to 50% AMI",
    household_income == "household income is greater than 50% but less than or equal to 80% of HAMFI" ~ "51 to 80% AMI",
    household_income == "household income is greater than 80% but less than or equal to 100% of HAMFI" ~ "81 to 100% AMI", 
    household_income == "household income is greater than 100% of HAMFI" ~ "101% AMI or greater"
  )) |> 
  mutate(household_type = case_when(
    household_type == "household type is elderly family (2 persons, with either or both age 62 or over)" ~ "Elderly family",
    household_type == "household type is small family (2 persons, neither person 62 years or over, or 3 or 4 persons)" ~ "Small family",
    household_type == "household type is large family (5 or more persons)" ~ "Large family",
    household_type == "household type is elderly non-family" ~ "Elderly non-family", 
    household_type == "other household type (non-elderly non-family)" ~ "Non-elderly non-family"
  ))  |> 
  mutate(cost_burden = case_when(
    cost_burden == "housing cost burden is less than or equal to 30%" ~ "Not cost-burdened", 
    cost_burden == "housing cost burden is greater than 30% but less than or equal to 50%" ~ "Cost-burdened",
    cost_burden == "housing cost burden is greater than 50%" ~ "Severely cost-burdened",
    cost_burden == "housing cost burden not computed (household has no/negative income)" ~ "No or negative income"
  )) |> 
  mutate(cb_group = case_when(
    cost_burden == "Cost-burdened" ~ "Cost-burdened",
    cost_burden == "Severely cost-burdened" ~ "Cost-burdened",
    cost_burden == "No or negative income" ~ "Cost-burdened",
    TRUE ~ cost_burden
  ))

pha_localities <- c("Richmond city", "Chesterfield County", "Hanover County", "Henrico County")

cb_7_pha <- cb_7 |> 
  subset(county %in% pha_localities) |> 
  group_by(year, household_income, cb_group) |> 
  summarise(estimate = sum(estimate)) |> 
  pivot_wider(
    names_from = year,
    values_from = estimate
  ) |> 
  clean_names() |> 
  transform(difference = (x2018 - x2015))

cb_income_pha <- cb_7_pha |> 
  filter(cb_group == "Cost-burdened")
  
gg_bar_col(cb_income_pha,
                 x_var = household_income,
                 y_var = difference,
                 col_var = household_income
) +
  scale_x_discrete(limits= c("30% AMI or less", "31 to 50% AMI", "51 to 80% AMI", "81 to 100% AMI", "101% AMI or greater")) + theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Cost burden from 2015 to 2018") +
  theme(legend.position = "none")

income_pha_perc <- cb_7 |> 
  subset(county %in% pha_localities) |> 
  group_by(year, county, household_income, cb_group) |>
  summarise(estimate = sum(estimate))

income_pha_perc <- income_pha_perc |> 
  transform(percent = ave(estimate, year, county, FUN = prop.table))

income_pha_perc_18 <- income_pha_perc |> 
  filter(year == 2018)

gg_bar_col(income_pha_perc_18,
                 x_var = county,
                 y_var = percent,
                 col_var = cb_group,
                 stack = TRUE)


```

```{r cb-tenure}

cb_tenure_pha <- cb_7 |> 
  subset(county %in% pha_localities) |> 
  group_by(year, county, tenure, cb_group) |> 
  summarise(estimate = sum(estimate)) |> 
  pivot_wider(
    names_from = year,
    values_from = estimate
  ) |> 
  clean_names() |> 
  transform(difference = (x2018 - x2015))

cb_tenure_pha <- cb_tenure_pha |> 
  filter(cb_group == "Cost-burdened")
  
gg_bar_col_facet(cb_tenure_pha,
                 x_var = county,
                 y_var = difference,
                 col_var = tenure,
                 facet_var = tenure
) +
  labs(title = "Cost burden from 2015 to 2018") +
  theme(legend.position = "none") + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1))


```

```{r cb-hh}


```

Mortgage delinquency and foreclosure

```{r mort-del}


```


Eviction filings and judgements
```{r evictions}

```

Housing Resource Line
```{r call-vol}

```

```{r call-topic}

```


Homelessness
```{r pit}

```


```{r mkv}

```

