# (PART)GAP ANALYSIS {.unnumbered}

## Affordability of current housing stock {#part-3-1}

```{r setup}

library(janitor)
library(optiRum)
library(tidyverse)
library(scales)

pha <- c("51085", "51760", "51087", "51041")

```

Rental housing gap
```{r gap}

tb_18a <- read_csv("data/Table18A_2015to2018.csv")
tb_18b <- read_csv("data/Table18B_2015to2018.csv")
tb_18c <- read_csv("data/Table18C_2015to2018.csv")

tb_18 <- rbind(tb_18a, tb_18b)

colnames(tb_18)[16] <- "Cost"

colnames(tb_18c)[16] <- "Cost"

homeowner <- rbind(tb_18, tb_18c) |> 
  clean_names() |> 
  filter(line_type == "Detail") |> 
  select(county, fips, year, estimate, tenure, cost, household_income) |> 
  group_by(county, fips, year, tenure, cost, household_income) |> 
  summarise(estimate = sum(estimate)) |> 
  subset(fips %in% pha)

tb_18_match <- tb_18_combined |> 
  filter(tenure == "Renter occupied") |>
  mutate(cost = case_when(
    cost == "greater than RHUD30 and less than or equal to RHUD50" ~ "31 to 50 percent AMI",
    cost == "greater than RHUD50 and less than or equal to RHUD80" ~ "51 to 80 percent AMI",
    cost == "greater than RHUD80" ~ "80 percent AMI or greater",
    cost == "less than or equal to RHUD30" ~ "30 percent AMI or below"
  )) |> 
  mutate(household_income = case_when(
    household_income == "greater than 100% of HAMFI" ~ "80 percent AMI or greater",
    household_income == "greater than 80% of HAMFI but less than or equal to 100% of HAMFI" ~ "80 percent AMI or greater",
    household_income == "greater than 50% of HAMFI but less than or equal to 80% of HAMFI" ~ "51 to 80 percent AMI",
    household_income == "greater than 30% of HAMFI but less than or equal to 50% of HAMFI" ~ "31 to 50 percent AMI", 
    household_income == "less than or equal to 30% of HAMFI" ~ "30 percent AMI or below"
  )) |> 
  group_by(county, fips, year, cost, household_income) |> 
  summarise(estimate = sum(estimate)) |> 
  mutate(match = case_when(
    cost == household_income ~ "Affordable",
    cost == "30 percent AMI or below" & household_income == "31 to 50 percent AMI" ~ "Very affordable", 
    cost == "30 percent AMI or below" & household_income == "51 to 80 percent AMI" ~ "Very affordable",
    cost == "30 percent AMI or below" & household_income == "80 percent AMI or greater" ~ "Very affordable",
        cost == "31 to 50 percent AMI" & household_income == "31 to 50 percent AMI" ~ "Affordable", 
    cost == "31 to 50 percent AMI" & household_income == "51 to 80 percent AMI" ~ "Very affordable",
    cost == "31 to 50 percent AMI" & household_income == "80 percent AMI or greater" ~ "Very affordable",
        cost == "31 to 50 percent AMI" & household_income == "30 percent AMI or below" ~ "Unaffordable",
    cost == "51 to 80 percent AMI" & household_income == "30 percent AMI or below" ~ "Unaffordable",
        cost == "51 to 80 percent AMI" & household_income == "31 to 50 percent AMI" ~ "Unaffordable",
    cost == "51 to 80 percent AMI" & household_income == "80 percent AMI or greater" ~ "Very affordable",
    cost == "80 percent AMI or greater" & household_income == "30 percent AMI or below" ~ "Unaffordable",
    cost == "80 percent AMI or greater" & household_income == "31 to 50 percent AMI" ~ "Unaffordable", 
    cost == "80 percent AMI or greater" & household_income == "51 to 80 percent AMI" ~ "Unaffordable"
  )) |> 
  mutate(gapcode = case_when(
    match == "Unaffordable" ~ "Gap",
    TRUE ~ "Matches or less than income"
  ))

gap <- tb_18_match |> 
  group_by(year, household_income, gapcode) |> 
  summarise(estimate = sum(estimate)) |> 
  mutate(estimate = case_when(
    gapcode == "Gap" ~ estimate * -1,
    gapcode == "Matches or less than income" ~ estimate
  )) |> 
  filter(household_income != "80 percent AMI or greater")

ggplot(gap,
       aes(x = year, 
           y = estimate,
           fill = gapcode)) +
  geom_bar(stat = "identity") +
  facet_grid(~household_income)



```

Income versus affordability
```{r renter-rent}

# Compare renter income versus rental prices

renter_income <- b25119_cpi |> 
  filter(tenure == "Renter")
  

pha_rent_annual <- read_csv("data/pha_rent_annual.csv") |> 
  rename(year = period)

rent_income <- renter_income |> 
  left_join(pha_rent_annual, by = "year")

rent_income_gap <- rent_income |> 
  mutate(affordable_rent = (dollars20/12)*.30) |> 
  mutate(difference = rent_current - affordable_rent) |> 
  pivot_longer(4:8,
               names_to = "type",
               values_to = "dollars") |> 
  filter(type == "rent_infl" | type == "affordable_rent") |> 
  mutate(type = case_when(
    type == "rent_infl" ~ "Average market rent",
    type == "affordable_rent" ~ "Rent affordable to typical renter"
  ))
  

ggplot(rent_income_gap,
       aes(x = year,
           y = dollars,
           color = type
        )) +
  geom_line(stat = "identity", size = 1) +
  facet_wrap(~locality) +
  scale_y_continuous(labels = dollar_format()) +
  theme(axis.title = element_blank(),
        axis.text.x = element_text(angle = 90, hjust = 1, vjust = 1)) +
  labs(title = "Market asking rent versus rent affordable", color = "Rent (2020 inflation-adjusted dollars)")
  

```

```{r  renter-own}

#Compare renter income versus home prices

renter_income <- b25119_cpi |> 
  filter(tenure == "Renter")

pha_sales_annual <- read_csv("data/pha_sales_annual.csv") |> 
  clean_names() |> 
  rename(year = primary_year, price = sale_price_median)

int_annual <- read_csv("data/fredmac_int_annual.csv")

downpayment <- 0.05 # 5% downpayment
closingcosts <- 0.015 # 1.5% closing costs
utilities <- 250 # Assume $250/month for utilities

sale_income <- renter_income |> 
  right_join(pha_sales_annual, by = "year") |> 
  right_join(int_annual, by = "year") |> 
  drop_na() |> 
  mutate(price = parse_number(price)) |> 
  mutate(principal = price - (price*downpayment)) |> 
  mutate(loanamt = principal/(1-closingcosts)) |> 
  mutate(mortgage = abs(PMT((annual_int/12), 360, loanamt)) + 250) |> 
  mutate(inc_needed = ((mortgage*10)/2.8)*12) |> 
  pivot_longer(4:10,
               names_to = "data",
               values_to = "value") |> 
  filter(data == "dollars20" | data == "inc_needed")

sale_income_gap <- sale_income |> 
  mutate(data = case_when(
    data == "dollars20" ~ "Renter median household income",
    data == "inc_needed" ~ "Income needed to afford median home price"
  ))

ggplot(sale_income_gap,
       aes(x = year, 
           y = value,
           color = data)) +
  geom_line(stat = "identity", size = 1) +
  facet_wrap(~locality) +
  labs(title = "Median home price versus renter income", color = "2020 inflation-adjusted dollars") +
  theme(axis.title = element_blank()) +
  scale_y_continuous(labels = dollar_format())


```

```{r occupations}


```

Ratio
```{r ratio}

# Income of five most common job sectors/occupations versus rental and home prices

```