# Town of Ashland {#part-4-9}

This chapter is a summary of the major changes to the Town of Ashland's population and housing market in the past five years.

```{r}
#| label: setup

library(tidyverse)
library(tidycensus)
library(sf)
library(sp)
library(plotly)
library(simplevis)
library(tidytext)
library(scales)
library(readxl)
library(zoo)
library(lubridate)
library(janitor)
library(viridis)
library(kableExtra)

tenure <- c("Homeowner", "Renter")
tenure_colors <-setNames(viridis(2), nm = tenure)

```

## Takeaways


## Demographic and socioeconomic changes

### Population changes


```{r}
#| label: pop-data


ashland_pop <- get_estimates(
  geography = "place",
  state = "VA",
  variables = "POP",
  year = 2019,
  time_series = TRUE
) %>% 
  filter(NAME == "Ashland town, Virginia")

ashland_20 <- get_decennial(
  geography = "place",
  state = "VA",
  year = 2020,
  sumfile = "pl",
  variables = "P1_001N"
) %>% 
  filter(NAME == "Ashland town, Virginia")

ashpop_clean <- ashland_pop |>
  filter(!DATE %in% c(2, 3)) |> # Remove non-decennial 2010 counts
  mutate(year = # Translate date codes into years
    case_when(
      DATE == 1 ~ "2010",
      DATE == 4 ~ "2011",
      DATE == 5 ~ "2012",
      DATE == 6 ~ "2013",
      DATE == 7 ~ "2014",
      DATE == 8 ~ "2015",
      DATE == 9 ~ "2016",
      DATE == 10 ~ "2017",
      DATE == 11 ~ "2018",
      DATE == 12 ~ "2019")) |> 
  mutate(counttype = # Add descriptions to count types
      case_when(
        DATE == 1 ~ "Census population",
        TRUE ~ "Population estimate")) |> 
  select( # Simplify columns
    GEOID,
    year,
    counttype,
    value
  )

# Prep total population counts from 2020 Census summary file

census_clean <- ashland_20 |> 
  mutate(year = "2020", # Add year and count type columns
         counttype = "Census population") |>
  select( # Simplify columns
    GEOID,
    year,
    counttype,
    value
  )

population_data <- ashpop_clean |> 
  bind_rows(census_clean)

```

```{r}
#| label: fig-ash-pop
#| fig-cap: "Town of Ashland: Total Population"

 ggplot(population_data,
        aes(x = year,
            y = value,
            fill = value)) +
  geom_col() +
  scale_fill_continuous(viridis_pal()) +
  labs(title = "Town of Ashland: Total Population",
       subtitle = "2010 to 2020",
       caption = "Source: U.S. Census Bureau Decennial Census and American Community Survey.") +
  scale_y_continuous(labels = label_comma()) +
  theme(axis.title = element_blank(),
        legend.position = "none",
        panel.background = element_blank(),
        axis.ticks = element_blank(),
        panel.grid.major.y = element_line(color = "grey95",
                                          size = 0.05))


```
```{r}
#| label: pop-forecasts

years <- c(2020, 2030, 2040, 2050)
estimate <- c(7565, 8142, 8824, 9638)
type <- c("Census", "Forecast", "Forecast", "Forecast")

forecast <- data.frame(year = years,
                       estimate = estimate,
                       type = type)


ggplot(forecast,
       aes(x = year,
           y = estimate,
           fill = type,
           label = label_comma()(estimate))) +
  geom_col() +
  geom_text(vjust= 1.5,
            color="white",
            size = 3,
            fontface="bold") +
  scale_y_continuous(labels = label_comma()) +
  theme(axis.title = element_blank(),
        axis.ticks = element_blank(),
        panel.grid.major.y = element_line(color = "grey95",
                                          size = 0.05),
        panel.background = element_blank()) +
  labs(title="Town of Ashland: Population projections",
       subtitle="Town Population in 2020 and forecast to 2050",
       fill="Estimate type",
       caption="Source: University of Virginia Weldon Cooper Center for Public Service")


  

```


### Household characteristics



```{r}
#| label: hh-age-data
#| eval: FALSE

years <- 2016:2020

b25007_vars <- load_variables(2020, "acs5") |>
  filter(str_sub(name, end = 6) %in% "B25007")

b25007_raw <- map_dfr(years, function(yr){
  b25007_pull <- get_acs(
    geography = "place",
    state = "VA",
    table = "B25007",
    year = yr,
    survey = "acs5",
    cache_table = TRUE
  ) |>
    mutate(year = yr)
}) %>% 
  filter(NAME == "Ashland town, Virginia")


b25007_vars_cleaned <- b25007_vars |>
  separate(label, into = c("est", "total", "tenure", "age"), sep = "!!") |>
  select(variable = name, tenure, age) |>
  drop_na() |>
  mutate(tenure = case_when(
    tenure == "Owner occupied:" ~ "Homeowner",
    tenure == "Renter occupied:" ~ "Renter"
  ))

b25007_data <- b25007_raw |>
  right_join(b25007_vars_cleaned, by = "variable") |>
  select(NAME, GEOID, year, tenure, age, estimate, moe) |>
  mutate(NAME = str_remove_all(NAME, "town, Virginia")) |>
  mutate(age = case_when(
    age == "Householder 15 to 24 years" ~ "Under 25 years old",
    age == "Householder 25 to 34 years" ~ "25 to 44 years old",
    age == "Householder 35 to 44 years" ~ "25 to 44 years old",
    age == "Householder 45 to 54 years" ~ "45 to 64 years old",
    age == "Householder 55 to 59 years" ~ "45 to 64 years old",
    age == "Householder 60 to 64 years" ~ "45 to 64 years old",
    age == "Householder 65 to 74 years" ~ "65 years and over",
    age == "Householder 75 to 84 years" ~ "65 years and over",
    age == "Householder 85 years and over" ~ "65 years and over"
  )) |>
  group_by(year, tenure, age) |>
  summarise(estimate = sum(estimate)) |>
  pivot_wider(names_from = year,
              values_from = estimate) |>
  select(tenure, age, `2016`, `2020`) |>
  transform(change = `2020` - `2016`) |>
  group_by(tenure, age) |>
  summarise(change = sum(change)) |>
  mutate(age = fct_relevel(age, "Under 25 years old")) |> 
  group_by(tenure, age) |> 
  summarise(change = sum(change))
```

```{r}
#| label: fig-hh-age-plot
#| fig.cap: "Change in households by age and tenure"

ggplot(b25007_data,
       aes(y = change, x =tenure, fill = tenure)) +
  geom_col(position = "dodge") +
  facet_wrap(~age, nrow = 1) +
  scale_y_continuous(labels = label_comma()) +
  labs(title="Change in households by age and tenure",
       subtitle="2016 to 2020",
       fill="Tenure",
       caption = "Source: U.S. Census Bureau, American Community Survey, Table B25007.") +
  theme(axis.title = element_blank(),
        axis.text.x = element_blank(),
        panel.background = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(color = "grey95",
                                          size = 0.05),
        axis.ticks = element_blank()) +
  scale_fill_manual(values = tenure_colors)

```

```{r}
#| label: hh-child-data
#| eval: FALSE
#| 
years <- 2016:2020

b25115_vars <- load_variables(2020, "acs5") |>
  filter(str_sub(name, end = 6) %in% "B25115")

b25115_raw <- map_dfr(years, function(yr){
  b25115_pull <- get_acs(
    geography = "place",
    state = "VA",
    table = "B25115",
    year = yr,
    survey = "acs5"
  ) |>
    mutate(year = yr)
}) %>% 
  filter(NAME == "Ashland town, Virginia")


b25115_vars_cleaned <- b25115_vars |>
  separate(label, into = c("est", "total", "tenure", "family", "type", "rel", "children"), sep = "!!") |>
  select(variable = name, tenure, family, type, rel, children) |>
  mutate(tenure = case_when(
    tenure == "Owner occupied:" ~ "Homeowner",
    tenure == "Renter occupied:" ~ "Renter"
  )) |>
  mutate(family = case_when(
    family == "Family households:" ~ "Family household",
    family == "Nonfamily households" ~ "Nonfamily household"
  )) |>
  mutate(type = case_when(
    type == "Married-couple family:" ~ "Married household",
    rel == "Male householder, no spouse present:" ~ "Single male household",
    rel == "Female householder, no spouse present:" ~ "Single female household",
    family == "Nonfamily household" ~ "Nonfamily household"
  )) |>
  mutate(children = case_when(
    rel == "With own children of the householder under 18 years" ~ "With children",
    rel == "No own children of the householder under 18 years" ~ "No children",
    children == "No own children of the householder under 18 years" ~ "No children",
    children == "With own children of the householder under 18 years" ~ "With children",
    family == "Nonfamily household" ~ "Nonfamily household"
  )) |>
  select(variable, tenure, family, type, children) |>
  drop_na()

b25115_data <- b25115_raw |>
  right_join(b25115_vars_cleaned, by = "variable") |>
  select(GEOID, year, tenure, type, children, estimate) |>
  pivot_wider(names_from = year,
              values_from = estimate) |>
  transform(change = `2020` - `2016`) |>
  select(tenure, type, children, change) |>
  group_by(tenure, children) |>
  summarise(change = sum(change)) 

```

```{r}
#| label: fig-hh-child-plot
#| fig.cap: "Change in households with children by tenure"

ggplot(b25115_data,
       aes(x = children, y = change, fill = tenure)) +
  geom_col(position = "dodge") + 
  facet_wrap(~children, nrow = 1, scales = "free_x") +
  scale_y_continuous(labels = label_comma()) +
  labs(title = "Change in households with children by tenure",
       subtitle = "2016 to 2020",
       fill = "Tenure",
       caption = "Source: U.S. Census Bureau, American Community Survey, Table B25115.") +
  theme(axis.title = element_blank(),
        axis.text.x = element_blank(),
        panel.background = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(color = "grey95",
                                          size = 0.05),
        axis.ticks = element_blank()) +
  scale_fill_manual(values = tenure_colors)

```

```{r}
#| label: hh-seniors-data
#| eval: FALSE

years <- 2016:2020

b09020_vars <- load_variables(2020, "acs5") |>
  filter(str_sub(name, end = 6) %in% "B09020")

b09020_raw <- map_dfr(years, function(yr){
  b09020_pull <- get_acs(
    geography = "place",
    state = "VA",
    table = "B09020",
    year = yr,
    survey = "acs5"
  ) |>
    mutate(year = yr)
}) %>% 
  filter(NAME == "Ashland town, Virginia")

b09020_vars_cleaned <- b09020_vars |>
  separate(label, into = c("est", "total", "hhgq", "family", "relationship", "sex", "alone"), sep = "!!") |>
  select(variable = name, hhgq, family, relationship, alone) |>
  filter(!variable %in% c("B09020_001", "B09020_002", "B09020_003", "B09020_005", "B09020_006",
                          "B09020_012", "B09020_013", "B09020_014", "B09020_017")) |>
  mutate(relationship = case_when(
    relationship == "Spouse" ~ "With spouse",
    relationship == "Nonrelatives" ~ "With nonrelatives",
    relationship %in% c("Parent", "Parent-in-law", "Other relatives") ~ "With other relative(s)",
    hhgq == "In group quarters" ~ "Group quarters",
    !is.na(alone) ~ alone,
    TRUE ~ relationship
  )) |>
  mutate(family = case_when(
    family == "In family households:" ~ "Family",
    family == "In nonfamily households:" ~ "Nonfamily",
    hhgq == "In group quarters" ~ "Group quarters"
  )) |>
  mutate(across(.fns = ~str_remove_all(.x, ":"))) |>
  select(1,3,4)

b09020_data <- b09020_raw |>
  right_join(b09020_vars_cleaned, by = "variable") |>
  select(GEOID, year, family, relationship, estimate) |>
  group_by(year, family, relationship) |> 
  summarise(estimate = sum(estimate)) |> 
  pivot_wider(names_from = year,
              values_from = estimate) |>
  transform(change = `2020` - `2016`) |>
  select(family, relationship, change) |>
  group_by(family, relationship) |> 
  summarise(change = sum(change)) |> 
  ungroup() |>
  mutate(family = str_replace(family, "Group quarters", " "),
         family = fct_relevel(family, "Family", "Nonfamily", " "))

```


```{r}
#| label: fig-hh-seniors-plot
#| fig.cap: "Change in senior population by living arrangement"

ggplot(b09020_data,
       aes(y = reorder_within(relationship, change, family),
           x = change,
           fill = relationship)) +
  geom_col(position = "dodge") +
  scale_y_reordered() +
  scale_x_continuous(labels = label_comma()) +
  facet_grid(rows = vars(family), scales = "free_y", space = "free", switch = "y") +
  labs(title="Change in senior population by living arrangement",
       subtitle="2016 to 2020",
       fill="Tenure",
       caption = "Source: U.S. Census Bureau, American Community Survey, Table B09020.") +
  theme(axis.title = element_blank(),
        #axis.text.x = element_blank(),
        panel.background = element_blank(),
        panel.grid.major.y = element_blank(),
        legend.position = "none",
        panel.grid.major.x = element_line(color = "grey95",
                                          size = 0.05),
        axis.ticks = element_blank(),
        strip.placement = "outside",
        strip.text.y = element_text(angle = 0))

```


### Income and wages

```{r}
#| label: hh-inc-data
#| eval: FALSE


years <- 2016:2020

b25118_vars <- load_variables(2020, "acs5") |> 
  filter(str_sub(name, end = 6) %in% "B25118")

b25118_raw <- map_dfr(years, function(yr){
  b25118_pull <- get_acs(
    geography = "place",
    state = "VA",
    table = "B25118",
    year = yr,
    survey = "acs5",
    cache_table = TRUE
  ) |> 
    mutate(year = yr)
  }) %>% 
  filter(NAME == "Ashland town, Virginia")

b25118_vars_cleaned <- b25118_vars |> 
  separate(label, into = c("est", "total", "tenure", "income"), sep = "!!") |>  
  select(variable = name, tenure, income) |> 
  mutate(tenure = case_when(
    tenure == "Owner occupied:" ~ "Homeowner",
    tenure == "Renter occupied:" ~ "Renter"
  )) |> 
  drop_na()

b25118_data <- b25118_raw |> 
  right_join(b25118_vars_cleaned, by = "variable") |> 
  select(year, tenure, income, estimate) |> 
  mutate(income = case_when(
    income == "Less than $5,000" ~ "Less than $15,000",
    income == "$5,000 to $9,999" ~ "Less than $15,000",
    income == "$10,000 to $14,999" ~ "Less than $15,000",
    income == "$15,000 to $19,999" ~ "$15,000 to $24,999",
    income == "$$20,000 to $24,999" ~ "$15,000 to $24,999",
    income == "$25,000 to $34,999" ~ "$25,000 to $49,999",
    income == "$35,000 to $49,999" ~ "$25,000 to $49,999",
    income == "$50,000 to $74,999" ~ "$50,000 to $74,999",
    TRUE ~ income
  )) |> 
  group_by(year, tenure, income) |> 
  summarise(estimate = sum(estimate)) |> 
  filter(year %in% c(2016, 2020)) |> 
  pivot_wider(names_from = year,
              values_from = estimate) |>
  mutate(change = `2020` - `2016`,
         pct_change = change/`2016`)

```

```{r}
#| label: fig-hh-inc-plot
#| fig.cap: "Change households by tenure and income level"

ggplot(b25118_data, 
       aes(y = income,
           x = change,
           fill = tenure)) +
  geom_col(position = "dodge") +
  facet_grid(~tenure) +
  scale_x_continuous(labels = label_comma()) +
  scale_y_discrete(limits = c("Less than $15,000","$15,000 to $24,999",
                              "$25,000 to $49,999", "$50,000 to $74,999",
                              "$75,000 to $99,999", "$100,000 to $149,999",
                              "$150,000 or more"),
                   labels = function(x) str_wrap(x, width = 12)) +
  labs(title = "Change households by tenure and income level",
       subtitle="2016 to 2020",
       caption = "Source: U.S. Census Bureau, American Community Survey, Table B25118.") +
  theme(axis.title = element_blank(),
        panel.background = element_blank(),
        panel.grid.major.y = element_blank(),
        legend.position = "none",
        panel.grid.major.x = element_line(color = "grey95",
                                          size = 0.05),
        axis.ticks = element_blank()) +
  scale_fill_manual(values = tenure_colors)

```

### Persons with disabilities


```{r}
#| label: ind-liv-age-data
#| eval: FALSE

# Table B18107 Sex by age by independent living difficulty

# "Because of a physical, mental, or emotional problem, having difficulty doing errands alone such as visiting a doctor’s office or shopping (DOUT)."

years <- 2016:2020

b18107_vars <- load_variables(2020, "acs5") |> 
  filter(str_sub(name, end = 6) %in% "B18107")

b18107_raw <- map_dfr(years, function(yr){
  b10107_pull <- get_acs(
    geography = "place",
    state = "VA",
    table = "B18107",
    year = yr,
    survey = "acs5",
    cache_table = TRUE
  ) |> 
    mutate(year = yr)
  }) %>% 
  filter(NAME == "Ashland town, Virginia")

b18107_vars_cleaned <- b18107_vars |> 
  separate(label, into = c("est", "total", "sex", "age", "indliv"), sep = "!!") |> 
  select(variable = name, sex , age, indliv) |> 
  drop_na() |> 
  mutate(across(.fns = ~str_remove_all(.x, ":")))

b18107_data <- b18107_raw |> 
  right_join(b18107_vars_cleaned, by = "variable") |> 
  select(GEOID, year, sex, age, indliv, estimate) |> 
  group_by(year, age, indliv) |> 
  summarise(estimate = sum(estimate)) |> 
  filter(indliv == "With an independent living difficulty") |> 
  pivot_wider(names_from = year,
              values_from =  estimate) |> 
  transform(change = `2020` - `2016`) |> 
  group_by(age) |> 
  summarise(change = sum(change))

```



```{r}
#| label: fig-ind-liv-age-plot
#| fig.cap: "Net change in individuals with independent living difficulties by age"

ggplot(b18107_data,
       aes(x = age,
           y = change,
           fill = age)) +
  geom_col() +
  labs(title="Net change in individuals with independent living difficulties by age",
       subtitle="2016 to 2020",
       caption="Source: U.S. Census Bureau, American Community Survey, Table B18107.") +
  scale_y_continuous(labels = label_comma()) +
  theme(axis.title = element_blank(),
        axis.ticks = element_blank(),
        legend.position = "none",
        panel.background = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(color = "grey95",
                                          size = 0.05))

```
## Housing supply and market changes

### Homeownership

```{r}

ashland <- st_read('https://services2.arcgis.com/sKZWgJlU6SekCzQV/arcgis/rest/services/Ashland_Boundary/FeatureServer/0/query?outFields=*&where=1%3D1&f=geojson', quiet = TRUE)

leaflet(ashland) %>% 
  addTiles() %>% 
  addPolygons()

# Last five years from 2022-10-07

ashland_sales <- read_csv("data/ashland_mls_5yrsales.csv")



```
